# Generated by Django 2.2.5 on 2019-11-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_read_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='chats.Message', verbose_name='last read message'),
        ),
    ]
